version: '3.8'

services:
  database:
    image: postgres:15
    container_name: cidades_inteligentes_db
    restart: always
    environment:
      POSTGRES_DB: cidades_inteligentes
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cidades_inteligentes_api
    restart: always
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/cidades_inteligentes
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8080:8080"
    command: ["sh", "-c", "mvn clean package -DskipTests && java -jar target/cidades-inteligentes-1.0-SNAPSHOT.jar"]

volumes:
  postgres_data:
